name: Daily Kayak Data Update

on:
  schedule:
    - cron: '0 9 * * *'  # Runs every day at 9:00 AM UTC
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo without token auth
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # <-- Disable default token auth

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run kayak data script
        run: python kayak_data_export.py

      - name: Debug PAT_TOKEN presence
        run: echo "PAT_TOKEN is set"
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Configure git to use PAT for pushing
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git remote set-url origin https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}

      - name: Commit and push updates
        run: |
          git add kayak_conditions.csv
          git commit -m "Automated update of kayak_conditions.csv" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
